name: Update Chart

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecución diaria a medianoche UTC
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Descargar datos desde el servicio REST
      run: python fetch_data.py

    - name: Generar el gráfico
      run: python generate_chart.py

    - name: Subir los datos y gráficos como artefactos
      uses: actions/upload-artifact@v4
      with:
        name: datos-y-graficos
        path: |
          data/inversiones_data.json
          docs/index.html

    - name: Commit y push de los cambios
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add data/inversiones_data.json docs/index.html
        git commit -m "Actualización automática de datos y gráfico"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Descargar artefactos
      uses: actions/download-artifact@v4
      with:
        name: datos-y-graficos
        path: docs

    - name: Publicar en GitHub Pages
      uses: actions/deploy-pages@v2
