name: Actualizar datos y gráfico

on:
  schedule:
    - cron: "0 */4 * * *"  # Cada 4 horas
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar script para obtener datos
        run: python fetch_data.py

      - name: Generar gráfico
        run: python generate_chart.py

      - name: Configurar Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Agregar cambios y hacer commit
        run: |
          git add data/inversiones_data.json docs/index.html
          git commit -m "Actualización automática de datos y gráfico" || echo "Sin cambios para commitear"

      - name: Hacer pull con rebase y push
        run: |
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
