name: Actualizar Datos y Generar Gráfico

on:
  schedule:
    - cron: "0 */4 * * *"  # Se ejecuta cada 4 horas
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pandas plotly pytz requests

      - name: Descargar datos desde la API
        run: |
          python fetch_data.py  # Reemplázalo con el script que obtiene los datos

      - name: Generar gráfico
        run: |
          python generate_chart.py

      - name: Mover `index.html` a la raíz del sitio
        run: |
          mkdir -p _site
          cp templates/index.html _site/index.html
          cp -r grafico _site/

      - name: Commit y push de los cambios
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add grafico/chart.html
          git commit -m "Actualizar gráfico generado automáticamente" || echo "No hay cambios que hacer commit"
          git push https://github.com/joseluisgch/inversionpublica_2025.git HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
