name: Update Chart

on:
  schedule:
    - cron: "0 */8 * * *"  # Cada 8 horas
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Instalar dependencias
      run: |
        pip install -r requirements.txt

    - name: Descargar datos
      run: python fetch_data.py

    - name: Generar gráfico
      run: python generate_chart.py  # Asegúrate que guarde el HTML en docs/

    - name: Subir artefacto para Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: docs/  # ¡Esta carpeta debe contener tu index.html!

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Desplegar
      uses: actions/deploy-pages@v2
      id: deployment
