name: Actualizar Datos y Generar Gráfico

on:
  schedule:
    - cron: "0 */4 * * *"  # Se ejecuta cada 4 horas
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pandas plotly pytz requests

      - name: Descargar datos desde la API
        run: |
          python fetch_data.py  # Reemplázalo con el script que obtiene los datos

      - name: Generar gráfico
        run: |
          python generate_chart.py

      - name: Subir cambios al repositorio
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Actualizar datos y gráfico automáticamente" || echo "No hay cambios para hacer commit"
          git push origin main
