name: Update Chart

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecución diaria a medianoche UTC
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Descargar datos desde el servicio REST
      run: python fetch_data.py

    - name: Generar el gráfico
      run: python generate_chart.py

    - name: Publicar en GitHub Pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: grafico

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Desplegar en GitHub Pages
      uses: actions/deploy-pages@v1
