name: Actualizar Datos JSON

on:
  schedule:
    - cron: "0 */4 * * *"  # Se ejecuta cada 4 horas
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script de actualización
        run: python fetch_data.py

      - name: Subir archivo actualizado
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/inversiones_data.json
          git commit -m "Actualización automática del JSON"
          git push
